### ISSUE TITLE
Failed to activate the cursor-history package

### ISSUE THREAD

**Issue by deprosun** [t9md/atom-cursor-history#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [cursor-history](https://github.com/t9md/atom-cursor-history) package, v0.5.5
### Stack Trace

Failed to activate the cursor-history package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.observeCommands (/home/karan/.atom/packages/cursor-history/lib/main.coffee:111:38)
  at Object.module.exports.activate (/home/karan/.atom/packages/cursor-history/lib/main.coffee:39:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:465:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -0:09.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "autocomplete-plus-python-jedi"
    ]
  },
  "cursor-history": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-html, v0.7.2
color-picker, v1.7.0
cursor-history, v0.5.5
minimap, v4.10.0
react, v0.12.10

# Dev
No dev packages
```

**Comment by t9md** [comment]
Atom version need to be v1.0.8 above, I refined version specification in package.json.
If you want to use this package, upgrade Atom to latest version.

**Comment by deprosun** [comment]
Thank you :)
