### ISSUE TITLE
Uncaught TypeError: editor.isAlive is not a function

### ISSUE THREAD

**Issue by zenbro** [t9md/atom-cursor-history#39]
[Enter steps to reproduce:]

1. Open project and multiple tabs with files
2. Close atom and open again
3. Close any tab

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [cursor-history](https://github.com/t9md/atom-cursor-history) package 0.12.0

### Stack Trace

Uncaught TypeError: editor.isAlive is not a function

```
At /Users/i/.atom/packages/cursor-history/lib/entry.js:25

TypeError: editor.isAlive is not a function
    at /packages/cursor-history/lib/entry.js:25:28)
    at Function.deserialize (/packages/cursor-history/lib/entry.js:10:12)
    at Object.assign.entries.state.entries.map.map.entry (/packages/cursor-history/lib/history.js:28:71)
    at Array.map (native)
    at Function.deserialize (/packages/cursor-history/lib/history.js:28:52)
    at Object.getHistory (/packages/cursor-history/lib/main.js:94:19)
    at Object.checkLocationChange (/packages/cursor-history/lib/main.js:194:12)
    at setTimeout (/packages/cursor-history/lib/main.js:179:18)
```

### Commands

```
     -1:12.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  7x -0:08.3.0 core:close (div.panels-item)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
advanced-open-file 0.16.6 
aesthetic-ui 4.0.0 
align-regexp 0.4.0 
angularjs 0.4.0 
atom-beautify 0.30.5 
atom-jade 0.3.0 
atom-typescript 11.0.6 
auto-detect-indentation 1.3.0 
autocomplete-paths 2.5.0 
autoprefixer 3.7.1 
better-jellybeans-syntax 1.0.3 
blame 0.12.0 
bracket-padder 0.4.1 
busy-signal 1.4.3 
clip-history 0.4.0 
color-picker 2.2.5 
css-declaration-sorter 1.1.0 
cursor-history 0.12.0 
dash 1.7.1 
disable-keybindings 0.6.0 
django-templates 0.5.0 
emmet 2.4.3 
file-icons 2.1.10 
find-selection 0.16.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
go-debug 1.5.0 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-babel 2.71.0 
language-diff 0.7.0 
language-elixir 0.19.0 
language-ember-htmlbars 0.4.0 
language-graphql 0.9.0 
language-haml 0.25.1 
language-haskell 1.12.1 
language-latex 1.1.0 
language-liquid 0.6.0 
language-pascal 0.20.2 
language-rspec 0.6.3 
language-rust 0.4.12 
language-slim 0.5.0 
language-viml 1.1.4 
less-than-slash 0.17.0 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-erb 1.1.0 
linter-eslint 8.2.1 
linter-js-yaml 1.2.7 
linter-php 1.3.2 
linter-pylint 2.1.0 
linter-python 3.1.2 
linter-ruby 1.2.4 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.4 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
narrow 0.50.3 
persistent-undo 1.2.0 
pigments 0.40.2 
project-manager 3.3.5 
rails-transporter 1.7.1 
react-snippets 0.9.0 
relative-numbers 0.8.0 
release-notes 0.53.0 
remote-sync 4.1.5 
rspec-snippets 0.4.0 
ruby-block-converter 4.0.1 
ruby-test-switcher 1.2.3 
script 3.15.0 
seeing-is-believing 2.2.3 
split-diff 1.4.3 
todo-show 1.11.0 
vim-mode-plus 0.96.2 
```

**Comment by t9md** [comment]
I couldn't reproduce.
How is your config of cursor-history?
Can you reproduce always?

From your report, you seem to saying exception is happen at timing of closing tab, but exception throwing `isAlive` check is done at deserialize timing when cursor-history package is activated.
That's strange.

**Comment by zenbro** [comment]
I can't reproduce the problem either (after some time of using new version of Atom).
That's strange, but there is no problem now.

Thank you!

**Comment by t9md** [comment]
thanks.

**Comment by machristie** [comment]
I'm still getting this issue.

[Enter steps to reproduce:]

1. Click in an editor anywhere


**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [cursor-history](https://github.com/t9md/atom-cursor-history) package 0.12.0


### Stack Trace

Uncaught TypeError: editor.isAlive is not a function

```
At /Users/machrist/.atom/packages/cursor-history/lib/entry.js:25

TypeError: editor.isAlive is not a function
    at /packages/cursor-history/lib/entry.js:25:28)
    at Function.deserialize (/packages/cursor-history/lib/entry.js:10:12)
    at Object.assign.entries.state.entries.map.map.entry (/packages/cursor-history/lib/history.js:28:71)
    at Array.map (native)
    at Function.deserialize (/packages/cursor-history/lib/history.js:28:52)
    at Object.getHistory (/packages/cursor-history/lib/main.js:94:19)
    at Object.checkLocationChange (/packages/cursor-history/lib/main.js:205:12)
    at setTimeout (/packages/cursor-history/lib/main.js:135:43)
```

### Commands

```
     -1:15.6.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
     -1:14.9.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
     -1:14.4.0 vim-mode-plus:move-to-last-character-of-line (input.hidden-input)
  2x -1:13.8.0 vim-mode-plus:move-left (input.hidden-input)
     -1:11.9.0 vim-mode-plus:move-right (input.hidden-input)
 13x -1:10.7.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
     -1:06.3.0 vim-mode-plus:move-to-end-of-word (input.hidden-input)
     -1:04.2.0 vim-mode-plus:yank (input.hidden-input)
     -0:48.4.0 vim-mode-plus:move-to-last-line (input.hidden-input)
     -0:44.1.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.7 
autocomplete-paths 2.8.1 
busy-signal 1.4.3 
cursor-history 0.12.0 
date 1.2.2 
django-templates 0.5.0 
editorconfig 2.2.2 
ex-mode 0.18.0 
git-plus 7.9.3 
intentions 1.1.5 
language-apache 1.7.0 
language-blade 0.34.0 
language-ini 1.19.0 
language-restructuredtext 1.1.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-ui-default 1.6.8 
markdown-preview-plus 2.4.10 
minimap 4.29.6 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
split-diff 1.5.1 
trailing-spaces 0.4.0 
vim-mode-plus 1.0.0 
```
