### ISSUE TITLE
Uncaught TypeError: this.getHistory(...).log is not a function

### ISSUE THREAD

**Issue by kopischke** [t9md/atom-cursor-history#46]
### Steps to reproduce

1. open a file in Atom
2. move cursor to a location over the row delta limit
3. call `Cursor History: Dump History`

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: cursor-history package 0.13.0

### Stack Trace

Uncaught TypeError: this.getHistory(...).log is not a function

```
At /Users/martin/.atom/packages/cursor-history/lib/main.js:76

TypeError: this.getHistory(...).log is not a function
    at /packages/cursor-history/lib/main.js:76:64)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:18.9.0 command-palette:toggle (input.hidden-input)
     -2:17.9.0 core:backspace (input.hidden-input)
 10x -2:15.6.0 core:move-down (input.hidden-input)
  2x -2:13.3.0 core:move-up (input.hidden-input)
     -2:12 core:confirm (input.hidden-input)
     -2:12 cursor-history:next-within-editor (input.hidden-input)
     -2:08.2.0 command-palette:toggle (input.hidden-input)
     -2:02.9.0 cursor-history:prev-within-editor (input.hidden-input)
     -2:00.2.0 command-palette:toggle (input.hidden-input)
  7x -1:56.1.0 core:move-down (input.hidden-input)
  2x -1:54.6.0 core:move-up (input.hidden-input)
     -1:54 core:confirm (input.hidden-input)
     -1:54 cursor-history:next-within-editor (input.hidden-input)
     -0:39.2.0 command-palette:toggle (input.hidden-input)
     -0:32.3.0 core:confirm (input.hidden-input)
     -0:32.3.0 cursor-history:dump-history (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-coffeescript 1.0.1 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
aligner-typescript 1.0.0 
atom-ide-ui 0.9.2 
autocomplete-gemfile 0.0.5 
autocomplete-xml 0.9.4 
build 0.70.0 
build-osa 0.7.2 
build-rake 0.1.1 
busy-signal 1.4.3 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
cursor-history 0.13.0 
dash 1.7.1 
editorconfig 2.2.2 
ide-css 0.2.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.5 
ide-yaml 0.4.2 
js-refactor 0.7.5 
keymap-control 1.2.0 
language-applescript 0.3.0 
language-fish-shell 1.1.0 
language-javascript-jxa 0.2.8 
language-m 1.0.1 
language-markdown 0.25.1 
mac-move-and-select 0.3.0 
markdown-scroll-sync 2.1.2 
open-project-in-tower 1.4.0 
open-terminal-here 2.3.1 
plist-converter 0.2.0 
refactor 0.11.5 
ruby-solargraph 0.2.0 
script 3.17.3 
teacode-atom-helper 1.1.0 
todo-show 2.2.0 
tree-view-bundler 0.0.3 
update-changelogs 0.1.0 
vim-mode-plus 1.30.0 
```

**Comment by t9md** [comment]
thanks for reporting!
