### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by crucialfelix** [t9md/atom-cursor-history#8]
1. I opened a project
2. search for something. I am in the search results pane
3. opened symbol view (shift-command-r)
4. error

so nothing related to cursor position or any editable document at all.

it should just bail if its not in an editable document

thanks !

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [cursor-history](https://github.com/t9md/atom-cursor-history) package, v0.4.17
### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/crucial/.atom/packages/cursor-history/lib/main.coffee:246

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
  at Object.module.exports.getPosition (/Users/crucial/.atom/packages/cursor-history/lib/main.coffee:246:11)
  at withPanel.onDidShow (/Users/crucial/.atom/packages/cursor-history/lib/main.coffee:107:23)
  at /Users/crucial/.atom/packages/cursor-history/lib/main.coffee:70:50
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Panel.module.exports.Panel.show (/Applications/Atom.app/Contents/Resources/app.asar/src/panel.js:77:29)
  at ProjectView.module.exports.SymbolsView.attach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/symbols-view.js:177:18)
  at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/project-view.js:42:21)
  at atom-workspace.workspaceSubscription.atom.commands.add.symbols-view:toggle-project-symbols (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:14:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:44.1.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -0:41.3.0 project-find:show (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:40 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 symbols-view:toggle-project-symbols (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      ".DS_Store"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "cute-cursor",
      "language-go",
      "language-java",
      "syntax-settings",
      "term",
      "language-supercollider",
      "linter-rst",
      "rst-preview",
      "rst-preview",
      "atom-runner",
      "make-runner",
      "ide-haskell",
      "remote-edit",
      "atomatigit",
      "minimap-highlight-selected",
      "tabs-to-spaces",
      "atomic-emacs",
      "git-log",
      "autoflow",
      "autosave",
      "background-tips",
      "block-travel",
      "dash",
      "easy-motion",
      "gist-it",
      "git-blame",
      "git-difftool",
      "git-plus",
      "trailing-spaces",
      "project-colorize",
      "file-icons",
      "term2",
      "web-view",
      "atom-terminal",
      "command-logger",
      "css-color-highlighting",
      "editor-stats",
      "selection-count",
      "fancy-new-file",
      "language-clojure",
      "language-docker",
      "minimap-find-and-replace",
      "mobile-preview",
      "my-package",
      "sourcegraph-atom",
      "org",
      "paredit",
      "autocomplete",
      "jumpy",
      "atom-color-highlight",
      "angularjs-snippets",
      "todo-show",
      "autocomplete-jedi",
      "bezier-curve-editor",
      "coffee-lint",
      "python-jedi",
      "org-mode",
      "highlight-selected",
      "node-resolver",
      "next-occurrence",
      "linter-scss-lint",
      "linter-coffeelint",
      "Atom-Syntax-highlighting-for-Sass",
      "grunt-runner",
      "typewriter-sounds",
      "ide-flow",
      "atom-ctags",
      "linter-jscs"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-django, v0.3.0
atom-ternjs, v0.7.1
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.3
color-picker, v2.0.11
cursor-history, v0.4.17
django-templates, v0.5.0
editorconfig, v1.0.1
emmet, v2.3.12
javascript-snippets, v1.0.0
language-crontab, v0.1.0
language-jade, v0.6.2
language-restructuredtext, v0.7.0
language-swift, v0.4.0
last-cursor-position, v0.9.0
linter, v1.3.4
linter-csslint, v1.0.5
linter-jshint, v1.1.5
linter-jsxhint, v0.1.2
linter-pep8, v1.0.1
linter-pylint, v0.2.2
minimap, v4.12.2
pain-split, v1.4.0
pigments, v0.9.3
project-manager, v1.15.11
python-autopep8, v0.1.3
react, v0.12.6
regex-railroad-diagram, v0.8.4
rename-tabs, v0.1.1
set-syntax, v0.3.0
symbol-gen, v1.0.0
tree-view-git-status, v0.1.2
vim-mode, v0.57.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by crucialfelix** [comment]
Thanks !

**Comment by t9md** [comment]
Thank you, your issue report was very clear, so easy
 to fix.
